const navHome = document.querySelector(".header_nav_ul_li_home") 
const navWe = document.querySelector(".header_nav_ul_li_we")            
const navservices = document.querySelector(".header_nav_ul_li_services")
const navNews = document.querySelector(".header_nav_ul_li_news")
const navContact = document.querySelector(".header_nav_ul_li_contact")